definitions:
  handler.SendMessage:
    properties:
      content:
        type: string
      path:
        type: string
      title:
        type: string
      to_list:
        items:
          type: string
        type: array
    type: object
info:
  contact: {}
  description: XXXXXXXXXXX
  license: {}
  title: Future对外开放API
  version: "1.0"
paths:
  /send:
    put:
      consumes:
      - application/json
      parameters:
      - description: input
        in: body
        name: account
        required: true
        schema:
          $ref: '#/definitions/handler.SendMessage'
          type: object
      - description: 授权码
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
        "400":
          description: ok
          schema:
            type: string
        "404":
          description: ok
          schema:
            type: string
        "500":
          description: ok
          schema:
            type: string
      tags:
      - 发送消息
swagger: "2.0"
